flowchart TD

    subgraph NavBar [Barre de navigation]
        NavA[Home]
        NavB[Projects]
        NavD[About Me]
    end

    PageA[Homepage]
    PageB[Projects Section]
    PageD[About Me Section]

    NavA --> PageA
    NavB --> PageB
    NavD --> PageD

    PageA --> PageB
    PageA --> PageD
    
    PageB --> P["Project Detail <br/> (GitHub / Live Demo Links)"]
    P --> PageB
